### ISSUE TITLE
Clear the `examples` directory before downloading examples

### ISSUE THREAD

**Issue by fturmel** [nature-of-code/fetch-notion#10]
Can I suggest you empty or delete the `./examples` directory before the sync process takes place? (probably early in `main.js`)

Deleted files from previously downloaded sketches, as well as old sketches no longer referenced in the NoC book, are not being removed.

All sketch files are always downloaded every time, so there's no downside to doing this imo - and the NoC repo will more accurately represent the current state of the embedded examples.

**Comment by shiffman** [comment]
I think this is a good idea! @jasongao97 what do you think?

**Comment by jasongao97** [comment]
Yes, that make sense! I'll make that change. Thanks!

**Comment by jasongao97** [comment]
Thank you! This is updated.

**Comment by fturmel** [comment]
@jasongao97 Great!

In case you missed it and assuming that https://github.com/nature-of-code/noc-book-2023/pull/469 was a (failed) test for this PR, the manual build step wasn't run after #11 was merged.

**Comment by jasongao97** [comment]
@fturmel Thank you so much for pointing that out! 😂 I always forget that.

**Comment by fturmel** [comment]
Glad it was helpful, and thanks for publishing the fix!
